version: "2"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www
    volumes:
    - .:/var/www
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    links:
    - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    working_dir: /var/www
    volumes:
    - .:/var/www
    links:
    - mysql
    - redis
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=mysql"
    - "REDIS_PORT=6379"
    - "REDIS_HOST=redis"
    user: ${CURRENT_UID}
  node:
    image: node:latest
    container_name: node
    volumes:
    - ./:/var/www
    working_dir: /var/www
    tty: true

  redis:
    image: redis:alpine
    container_name: redis
    ports:
    - "63791:6379"

  mysql:
    image: mysql:5.7
    volumes:
    - ./storage/mysql:/var/lib/mysql
    environment:
    - "MYSQL_ROOT_PASSWORD=secret"
    - "MYSQL_USER=app"
    - "MYSQL_PASSWORD=secret"
    - "MYSQL_DATABASE=app"
    ports:
    - "33061:3306"