version: "2"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www
    links:
      - mysql
      - redis

  node:
    image: node:8.6-alpine
    container_name: node
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "63791:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    working_dir: /var/www
    volumes:
      - ./application/:/var/www
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
    ports:
      - "33061:3306"
